manifest:
  remotes:
    - name: joshajohnson
      url-base: https://github.com/joshajohnson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: chalice
      import: app/west.yml
  self:
    path: config
